name: Com Flow

on:
  push:
    paths:
      - 'Records/ComFlow.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
 #############################################################################################      
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_NAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://fsgsh:${{ secrets.github.token }}@github.com" > ~/.git-credentials
#############################################################################################
       - name: Apt Update packages and Upgrade them.
         run: |
            sudo su && sudo apt update -y && sudo apt upgrade -y
#############################################################################################
       - name: Specs Check
         run: |
            bash specs.sh
#############################################################################################
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GH_TOKEN }}
#############################################################################################
       - name: Cleaning up some space & Deploying and Running bot in ParallelParallel
         timeout-minutes: 340
         continue-on-error: true
         run: |
           parallel -j3 -u ::: 'sudo bash cleanup.sh' 'git clone -b main https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.GIT_NAME }}/VideoCompress.git combot && cd combot && sudo docker build . -t combot && sudo docker run combot' 'git clone -b hevc https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.GIT_NAME }}/VideoCompress.git hevcbot && cd hevcbot && sudo docker build . -t hevcbot && sudo docker run hevcbot'
#############################################################################################
       - name: Send Record to Github
         continue-on-error: true
         run: |
              git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} botflow
              cd botflow || exit 1
              echo $(TZ='${{ secrets.TZ }}' date) >> Records/ComFlow.txt
              git add Records/ComFlow.txt
              git commit -m "Workflow : add recorded loop to logs $(TZ='${{ secrets.TZ }}' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:master
